apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: demo-app-test
    app.kubernetes.io/name: demo-app
  name: demo-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: demo-app-test
      app.kubernetes.io/name: demo-app
      owner: deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: demo-app-test
        app.kubernetes.io/name: demo-app
        owner: deployment
    spec:
      containers:
        - image: registry.k8s.fscker.org/demo-app:0.1.15-87fcf4ea
          name: demo-app
          env:
            - name: A_PASSWORD_IN_PLAINTEXT
              value: hunter2
          ports:
            - containerPort: 5000
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
