apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nginx-static-app-test
    app.kubernetes.io/name: nginx-static-app
  name: nginx-static-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx-static-app-test
      app.kubernetes.io/name: nginx-static-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx-static-app-test
        app.kubernetes.io/name: nginx-static-app
    spec:
      containers:
        - image: leprechaun/nginx-static-app-on-k8s:e2c53626
          name: nginx-static-app-on-k8s
          env:
            - name: A_PASSWORD_IN_PLAINTEXT
              value: hunter2
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
