apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-app
  labels:
    app.kubernetes.io/instance: demo-app-test
    app.kubernetes.io/name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: demo-app-test
      app.kubernetes.io/name: demo-app
      owner: replicaset
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: demo-app-test
        app.kubernetes.io/name: demo-app
        owner: replicaset
    spec:
      containers:
      - image: leprechaun/demo-app:0.1.14-67911c24
        name: demo-app
        env:
          - name: A_PASSWORD_IN_PLAINTEXT
            value: hunter2
        ports:
          - containerPort: 5000
            name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
