apiVersion: v1
kind: Pod
metadata:
  name: nginx-static-app-on-k8s
  labels:
    name: nginx-static-app-on-k8s
    environment: staging
    arbitrary-key: arbitrary-value
spec:
  containers:
  - image: leprechaun/nginx-static-app-on-k8s:e2c53626
    name: nginx-static-app-on-k8s
    env:
      - name: A_PASSWORD_IN_PLAINTEXT
        value: hunter2
    ports:
      - containerPort: 8080
        name: http
    volumeMounts:
    - name: my-volume
      mountPath: /data/
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

  volumes:
  - name: my-volume
    emptyDir: {}
