apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: demo-app-with-env
    app.kubernetes.io/name: demo-app
  name: demo-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: demo-app-with-env
      app.kubernetes.io/name: demo-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: demo-app-with-env
        app.kubernetes.io/name: demo-app
    spec:
      containers:
        - image: leprechaun/demo-app:0.1.15-87fcf4ea
          name: demo-app
          env:
            - name: A_PASSWORD_IN_PLAINTEXT
              valueFrom:
                configMapKeyRef:
                  name: example-configmap
                  key: SOME_KEY
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
