apiVersion: v1
kind: Pod
metadata:
  name: demo-app-bare
  labels:
    arbitrary-key: arbitrary-value
spec:
  containers:
  - image: registry.k8s.fscker.org/demo-app:0.1.14-67911c24
    name: demo-app
    ports:
      - containerPort: 8080
        name: http
