kind: Service
apiVersion: v1
metadata:
  name: demo-app
spec:
  selector:
    app.kubernetes.io/instance: demo-app-test
    app.kubernetes.io/name: demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http
