kind: Service
apiVersion: v1
metadata:
  name: nginx-static-app-on-k8s
spec:
  selector:
    app.kubernetes.io/instance: nginx-static-app-test
    app.kubernetes.io/name: nginx-static-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
